#define _USE_MATH_DEFINES
#define INF numeric_limits<double>::infinity()
#define BigM  10000

#include "PartitionScheme.h"

void exit_error(int line_num) {
    fprintf(stderr, "error occured at line %d\n", line_num);
    exit(1);
}

void PartitionScheme::build(DataHandler& dataset, int nb_dstzn) {
	this->_dataset = &dataset;
	this->_nb_dstzn = nb_dstzn;
	_size_G = 2 * _dataset->_nb_targets * _nb_dstzn + 2;
	_G.resize(_size_G);
	for (int i = 0; i < _size_G; i++) {
		_G[i].resize(_size_G, make_pair(false, -1.0));
	}
	_min_risk_tars.resize(_dataset->_nb_targets + 2);
	for (int i = 0; i < _dataset->_nb_targets + 2; i++) {
		_min_risk_tars[i].resize(_dataset->_nb_targets + 2, 0); // either 0 or positive for building TSP model
	}
	this->_subarc_angle = 2.0 * M_PI / _nb_dstzn;
	// parameters initialization for risk & reward functions
	for (int i = 0; i < _dataset->_nb_targets; i++)
		_par_c1.push_back(1);
	for (int i = 0; i < _dataset->_nb_targets; i++) //let the best observation distance be half radius
		_par_optOBdist.push_back(_dataset->_radii[i]/2.0);
	for (int i = 0; i < _dataset->_nb_targets; i++)
		_par_varOBdist.push_back(1);
	_par_c_hat = 0.01;

	// valid edges on graph G is generated by the following steps
	build_nodes_crds();
	get_risk_reward_linearInnerTrajc();
	// add rotatory case
	get_risk_reward_outerTrajc(); // **Important**:'_min_risk_tars' is generated in this function.
}

void PartitionScheme::build_nodes_crds() {
	_points.resize(_dataset->_nb_targets + 2);
	_points[0].resize(1); //departure point
	_points[0][0] = _dataset->_depot1_loc;
	// _points[0][0].print();
	for (int pos = 0; pos < _dataset->_nb_targets; pos++) {
		_points[pos+1].resize(_nb_dstzn);
		for (int i = 0; i < _nb_dstzn; i++) {
			_points[pos+1][i]._x = _dataset->_radii[pos] * cos(i * _subarc_angle) + _dataset->_target_locs[pos]._x;
			_points[pos+1][i]._y = _dataset->_radii[pos] * sin(i * _subarc_angle) + _dataset->_target_locs[pos]._y;
			// _points[pos+1][i].print();
		}
	}
	_points[_dataset->_nb_targets + 1].resize(1); // landing depot
	_points[_dataset->_nb_targets + 1][0] = _dataset->_depot2_loc;
	// _points[_dataset->_nb_targets + 1][0].print();
}


/* 
	calculate risk&reward on all inner circle trajectories.
*/
void PartitionScheme::get_risk_reward_linearInnerTrajc() {
	int idx_row, idx_col, flag;
	double max_reward, max_risk;
	vector<double> risk_innerpath(_nb_dstzn, -1); // -1 means invalid risk or reward value
	vector<double> reward_innerpath(_nb_dstzn, -1);
	for (int s = 0; s < _dataset->_nb_targets; s++) { 
		max_reward = 0.0;
		max_risk = 0.0;
		for (int i = 0; i < _nb_dstzn; i++) {
			if (i == 0) { // entry point and exit point are the same
				risk_innerpath[i] = 0.0; // 0 means no risk or no reward
				reward_innerpath[i] = 0.0; //
			}
			else {
				/*  test the correctness by simply using euclidean distance */
				risk_innerpath[i] = get_lineSeg_len(_points[s+1][0], _points[s+1][i]);
				reward_innerpath[i] = get_lineSeg_len(_points[s+1][0], _points[s+1][i]);
				// risk_innerpath[i] = get_risk_linearInnerTrajc(_points[s+1][0], _points[s+1][i], s);
				// reward_innerpath[i] = get_reward_linearInnerTrajc(_points[s+1][0], _points[s+1][i], s);
				// cout << "target: " << s+1 << ": " <<risk_innerpath[i] << " " << reward_innerpath[i] << endl; 
				if (risk_innerpath[i] > max_risk && risk_innerpath[i] < BigM)
					max_risk = risk_innerpath[i];
				if (reward_innerpath[i] > max_reward && reward_innerpath[i] < BigM)
					max_reward = reward_innerpath[i];
			}
		}
		// cout << "Target: " << s+1 << " max risk: " <<  max_risk << endl;
		// cout << "Target: " << s+1 << " max reward: " << max_reward << endl;
		/* write inner risk&reward values to matrix G */ 
		idx_row = s * 2 * _nb_dstzn + 1; 
		idx_col = s * 2 * _nb_dstzn + _nb_dstzn + 1;
		for (int i = 0; i < _nb_dstzn; i++) {
			for (int j = 0; j < _nb_dstzn; j++) {
				flag = (_nb_dstzn - i + j) % _nb_dstzn;
				// if (risk_innerpath[flag] <= (max_risk*_dataset->_risk_thold_ratio[s]) && reward_innerpath[flag] >= (max_reward*_dataset->_bdg_rewards_ratio[s]))
				// 	_G[idx_row + i][idx_col + j] = make_pair(true,risk_innerpath[flag]);
				if (risk_innerpath[flag] <= _dataset->_risk_thold_ratio[s] && reward_innerpath[flag] >= _dataset->_bdg_rewards_ratio[s])
					_G[idx_row + i][idx_col + j] = make_pair(true,risk_innerpath[flag]);
			}
		}
	}
	/*print for debugging: */
	if(false){
		for (int i = 0; i < _size_G; i++) {
			for (int j = 0; j < _size_G; j++) {
				cout << _G[i][j].second << ' ';
			}
			cout << '\n';
		}
	}

}

double PartitionScheme::get_reward_linearInnerTrajc(Vertex entry, Vertex exit, int tar) { 
	double l1 = get_lineSeg_len(entry, exit) / 2.0;
	double l2 = sqrt(_dataset->_radii[tar] * _dataset->_radii[tar] - l1 *l1);
	double num_intervals = 200.0; // partition the half chord into num_interval pieces
	double len_interval = l1 / num_intervals;
	double total_reward = 0.0;
	double d, temp;
	for (int j = 0; j < num_intervals; j++) {
		d = sqrt(l2 *l2 + pow(len_interval * j, 2));
		temp = exp(-pow(d - _par_optOBdist[tar], 2) / (2 * pow(_par_varOBdist[tar], 2)));
		total_reward = total_reward + temp * len_interval;
	}
	total_reward = 2 * total_reward;
	return total_reward;
}

double PartitionScheme::get_risk_linearInnerTrajc(Vertex entry, Vertex exit, int tar) {
	double l1 = get_lineSeg_len(entry, exit) / 2.0;
	double l2 = sqrt(_dataset->_radii[tar] * _dataset->_radii[tar] - l1* l1);
	return inner_risk_function(l1, l2, tar);
}

void PartitionScheme::get_risk_reward_outerTrajc() {
	/* Generate the accumulated risk on outer paths*/
	int idxmat_1, idxmat_2, idxmat_3, idxmat_4;
	double val_risk, val_min_risk;
	/* i) departure depot --> each entry turning point of a target */
	for (int t = 1; t <= _dataset->_nb_targets; t++) {	
		idxmat_1 = (t - 1) * 2 * _nb_dstzn + 1; 
		val_min_risk = INF;
		for (int i = 0; i < _nb_dstzn; i++) {
			// val_risk = get_risk_outerTrajc(_points[t][i], _dataset->_depot1_loc);
			val_risk = get_lineSeg_len(_points[t][i], _dataset->_depot1_loc);
			_G[0][idxmat_1 + i] = make_pair(true, val_risk);
			// cout << _G[0][idxmat_1 + i].second << " ";
			if (val_risk < val_min_risk) {
				val_min_risk = val_risk;
			}
		}
		/*minimum risk matrix is symmetic*/
		_min_risk_tars[0][t] = val_min_risk;
		_min_risk_tars[t][0] = val_min_risk;
		// cout << " ====>> minimum risk from departure to target " << t << ": " << val_min_risk << endl;
	}
	/* each pair of entry and exit between targets*/
	for (int s = 1; s <= _dataset->_nb_targets; s++) { // ii) boundary s <-> boudary t
		idxmat_1 = (s - 1) * 2 * _nb_dstzn + _nb_dstzn + 1; // exit of target s
		idxmat_3 = (s - 1) * 2 * _nb_dstzn + 1; // entries  of target s
		for (int t = 1; t <= _dataset->_nb_targets; t++) {
			if(s != t){
				idxmat_2 = (t - 1) * 2 * _nb_dstzn + 1; // vertices on boundary t acted as entries
				idxmat_4 = (t - 1) * 2 * _nb_dstzn + _nb_dstzn + 1; // vertices on boundary t acted as exits
				val_min_risk = INF;
				for (int i = 0; i < _nb_dstzn; i++) {
					for (int j = 0; j < _nb_dstzn; j++) {
						// val_risk = get_risk_outerTrajc(_points[s][i], _points[t][j]);
						val_risk = get_lineSeg_len(_points[s][i], _points[t][j]); // for testing
						_G[idxmat_1 + i][idxmat_2 + j] = make_pair(true, val_risk);
						_G[idxmat_4 + j][idxmat_3 + i] = make_pair(true, val_risk);
						// cout << idxmat_1+i << "-->" << idxmat_2+j << " : " << _G[idxmat_1 + i][idxmat_2 + j].second << '\n';
						if (val_risk < val_min_risk)
							val_min_risk = val_risk;
					}
				}
				_min_risk_tars[s][t] = val_min_risk;
				_min_risk_tars[t][s] = val_min_risk;
				// cout << " ------ min-risk target s to target t: " << val_min_risk << endl;
			}
		}
	}
	/*all exits to arrival depot*/
	for (int s = 1; s <= _dataset->_nb_targets; s++) { 	
		idxmat_2 = (s - 1) * 2 * _nb_dstzn + _nb_dstzn + 1;
		val_min_risk = INF;
		for (int i = 0; i < _nb_dstzn; i++) {
			// val_risk = get_risk_outerTrajc(_points[s][i], _dataset->_depot2_loc);
			val_risk = get_lineSeg_len(_points[s][i], _dataset->_depot2_loc); // for testing 
			_G[idxmat_2 + i][_size_G - 1] = make_pair(true, val_risk);
			if (val_risk < val_min_risk)
				val_min_risk = val_risk;
		}
		_min_risk_tars[s][_dataset->_nb_targets + 1] = val_min_risk;
		_min_risk_tars[_dataset->_nb_targets + 1][s] = val_min_risk;
		// cout << " ------ depot 2 to target: " << val_min_risk << endl;
	}

	/* diagonal elements -- 
	for (s = 0; s <= _dataset->_nb_targets + 1; s++) {
		_min_risk_tars[s][s] = 0.0;
	}
	_min_risk_tars[0][_dataset->_nb_targets + 1] = 0.0;
	_min_risk_tars[_dataset->_nb_targets + 1][0] = 0.0;
	*/

	/*
	ofstream file_G("./matrixG.txt");
	for (int i = 0; i < _size_G; i++) {
		for (int j = 0; j < _size_G; j++) {
			file_G << _G[i][j].second << '\t';
		}
		file_G << '\n';
	}
	*/

	// ------------  Step 2: subtract the min_risk_mat[s][t] from G[i][j]   -------------
	if(true){
		for (int t = 1; t <= _dataset->_nb_targets; t++) {
		idxmat_1 = (t - 1) * 2 * _nb_dstzn + 1;
		idxmat_2 = (t - 1) * 2 * _nb_dstzn + _nb_dstzn + 1;
		for (int i = 0; i < _nb_dstzn; i++) {
			if(_G[0][idxmat_1 + i].first == true)
				_G[0][idxmat_1 + i].second -= _min_risk_tars[0][t];
		}
		}
		for (int s = 1; s <= _dataset->_nb_targets; s++) {
			idxmat_1 = (s - 1) * 2 * _nb_dstzn + _nb_dstzn + 1; // vertices worked as exits in boundary s
			idxmat_3 = (s - 1) * 2 * _nb_dstzn + 1; // vertices worked as entries in boundary s
			for (int t = 1; t <= _dataset->_nb_targets; t++) {
				if(s != t){
					idxmat_2 = (t - 1) * 2 * _nb_dstzn + 1; // vertices worked as entries on boundary t
					idxmat_4 = (t - 1) * 2 * _nb_dstzn + _nb_dstzn + 1; // vertices worked as exits on boundary t
					for (int i = 0; i < _nb_dstzn; i++) {
						for (int j = 0; j < _nb_dstzn; j++) {
							if(_G[idxmat_1 + i][idxmat_2 + j].first == true)
								_G[idxmat_1 + i][idxmat_2 + j].second -= _min_risk_tars[s][t];
							if(_G[idxmat_4 + j][idxmat_3 + i].first == true)
								_G[idxmat_4 + j][idxmat_3 + i].second -= _min_risk_tars[t][s];
						}
					}	
				}			
			}
		}
		for (int s = 1; s <= _dataset->_nb_targets; s++) {
			idxmat_2 = (s - 1) * 2 * _nb_dstzn + _nb_dstzn + 1;
			for (int i = 0; i < _nb_dstzn; i++) {
				if(_G[idxmat_2 + i][_size_G - 1].first == true)
					_G[idxmat_2 + i][_size_G - 1].second -= _min_risk_tars[s][_dataset->_nb_targets + 1];
			}
		}
	}
	

	/*print for debugging: */
	if(true){
		for (int i = 0; i < _size_G; i++) {
			for (int j = 0; j < _size_G; j++) {
				cout << _G[i][j].second << ' ';
			}
			cout << '\n';
		}
	}
	if(false){
		for (int s = 0; s < _dataset->_nb_targets+2; s++) {
			for (int t = 0; t < _dataset->_nb_targets+2; t++) {
				cout << _min_risk_tars[s][t] << ' ';
			}
			cout << '\n';
		}
	}

}

double PartitionScheme::get_risk_outerTrajc(Vertex v, Vertex u) {
	double total_risk = outer_risk_function(get_lineSeg_len(v, u)); // total risk over the line segment
	// cout << total_risk << "_*_";
	for (int i = 0; i < _dataset->_nb_targets; i++) { // additional possible risk caused when passing through some region(s)
		tuple<bool, double, double> result = is_intersected(v, u, i);
		// cout << get<0>(result) << "**" << get<1>(result) << "**"<<get<2>(result) << endl;
		if (get<0>(result) == true){ // if current straight line intersects with region Ui, we add additional risk to this outer path
			total_risk = total_risk + get<1>(result) - get<2>(result);
		}
	}
	// cout << total_risk << " ";
	return total_risk;
}

tuple<bool, double,double> PartitionScheme::is_intersected(Vertex v, Vertex u, int tar) {
	// current target center is denoted as o;
	Vertex o = { _dataset->_target_locs[tar]._x, _dataset->_target_locs[tar]._y };
	myVector v_2_o(v, o); // vector v->o
	myVector v_2_u(v, u); // vector v->u
	myVector o_2_u(o, u); // vector o->u
	double len_v_2_o = v_2_o.get_vecLen();
	double len_v_2_u = v_2_u.get_vecLen();
	double len_o_2_u = o_2_u.get_vecLen();	
	double angle = acos((len_o_2_u*len_o_2_u + len_v_2_u*len_v_2_u-len_v_2_o*len_v_2_o)/(2.0*len_o_2_u*len_v_2_u));
	double l2 = len_v_2_o * sin(angle); // vertical distance from center o to the chord
	double l1; // half length of the chord
	double risk_vu_on_Ui; // risk of path vu when passing through target region Ui
	if (l2 + 0.0000001 < _dataset->_radii[tar] && angle < (M_PI / 2.0) && len_v_2_o * cos(angle)+ 0.0000001 < len_v_2_u) {
		l1 = sqrt(_dataset->_radii[tar] * _dataset->_radii[tar] - l2 * l2);
		risk_vu_on_Ui = inner_risk_function(l1, l2, tar);
		// cout << "vo:" << len_v_2_o << " vu:" << len_v_2_u << " ou:" << len_o_2_u << endl;
		// cout << "v:" << v._x << "," << v._y << endl;
		// cout << "u:" << u._x << "," << u._y << endl;
		// cout << "o:" << o._x << "," << o._y << endl;
		// cout << len_v_2_u << " " << l1 << " " << l2 <<  " r=" << _dataset->_radii[tar] << endl;
		return make_tuple(true, risk_vu_on_Ui, outer_risk_function(2 * l1));
	}
	else {
		return make_tuple(false, NULL, NULL);
	}
}

double PartitionScheme::inner_risk_function(double l1, double l2, int tar) {
	double T = 2 * _par_c1[tar] * atan(l1 / l2) / l2;
	return T;
}

double PartitionScheme::outer_risk_function(double dist) {
	return _par_c_hat * dist;
}

double PartitionScheme::dot_product(myVector vec1, myVector vec2) {
	return vec1._x * vec2._x + vec1._y * vec2._y;
}


double PartitionScheme::get_lineSeg_len(Vertex v, Vertex u) {
	return sqrt(pow(u._x - v._x, 2) + pow(u._y - v._y, 2));
}

void PartitionScheme::solve_shortestpath(vector<int> & seq, vector<vector<double>> & SDS) {
	int idxmat_1, idxmat_2, idxmat_3;
	vector<double> entry_dist(_nb_dstzn, INF);
	vector<double> exit_dist(_nb_dstzn, INF);
	vector<double> INF_dist(_nb_dstzn, INF);
	double dist_endDepot = INF;

	double dist = 0.0;
	// i) SDS[start depot] = 0.0
	SDS[0].resize(1);
	SDS[0][0] = 0.0;

	// ii) SDS[*] of boundary points of the first visited target
	int pos = 1;
	int idx_circle = seq[pos];
	SDS[1].resize(_nb_dstzn);
	idxmat_1 = (idx_circle - 1) * 2 * _nb_dstzn + 1; //first entry of the first visited target
	for (int i = 0; i < _nb_dstzn; i++)	{
		if (_G[0][idxmat_1 + i].first == true) {
			entry_dist[i] = _G[0][idxmat_1 + i].second;
			SDS[1][i] = entry_dist[i];
		}
	}
	idxmat_2 = (idx_circle - 1) * 2 * _nb_dstzn + _nb_dstzn + 1;
	for (int i = 0; i < _nb_dstzn; i++) {
		for (int j = 0; j < _nb_dstzn; j++) {
			if (_G[idxmat_1 + i][idxmat_2 + j].first == true) {
				dist = entry_dist[i] + _G[idxmat_1 + i][idxmat_2 + j].second;
				if (dist < exit_dist[j])
					exit_dist[j] = dist;
			}
		}
	}
	entry_dist = INF_dist;

	// iii) nodes from seq[2] to seq[num_circles]
	int idx_fr_circle = 0;
	int idx_lat_circle = 0;
	for (pos = 2; pos <= _dataset->_nb_targets; pos++) {
		SDS[pos].resize(_nb_dstzn);
		idx_fr_circle = seq[pos - 1]; 
		idx_lat_circle = seq[pos]; 
		idxmat_1 = (idx_fr_circle - 1) * 2 * _nb_dstzn + _nb_dstzn + 1;
		idxmat_2 = (idx_lat_circle - 1) * 2 * _nb_dstzn + 1;
		for (int i = 0; i < _nb_dstzn; i++) {
			for (int j = 0; j < _nb_dstzn; j++) {
				if (_G[idxmat_1 + i][idxmat_2 + j].first == true) {
					dist = exit_dist[i] + _G[idxmat_1 + i][idxmat_2 + j].second;
					if (dist < entry_dist[j])
						entry_dist[j] = dist;
				}
			}
		}
		for (int i = 0; i < _nb_dstzn; i++) {
			SDS[pos][i] = entry_dist[i];
		}
		exit_dist = INF_dist;
		idxmat_3 = (idx_lat_circle - 1) * 2 * _nb_dstzn + _nb_dstzn + 1;
		// update exits
		for (int i = 0; i < _nb_dstzn; i++) {
			for (int j = 0; j < _nb_dstzn; j++) {
				if (_G[idxmat_2 + i][idxmat_3 + j].first == true) {
					dist = entry_dist[i] + _G[idxmat_2 + i][idxmat_3 + j].second;
					if (dist < exit_dist[j])
						exit_dist[j] = dist;
				}
			}
		}
		entry_dist = INF_dist;
	}
	// iv) the last target <-> the end depot
	idx_circle = seq[_dataset->_nb_targets];
	SDS[_dataset->_nb_targets + 1].resize(1);
	idxmat_1 = (idx_circle - 1) * 2 * _nb_dstzn + _nb_dstzn + 1;
	for (int i = 0; i < _nb_dstzn; i++) {
		if (_G[idxmat_1 + i][_size_G - 1].first == true) {
			dist = exit_dist[i] + _G[idxmat_1 + i][_size_G - 1].second;
			if (dist < dist_endDepot)
				dist_endDepot = dist;
		}
	}
	SDS[_dataset->_nb_targets + 1][0] = dist_endDepot;
}

double PartitionScheme::calc_sequence_distance(vector<int> & fseq_){
	double val = 0.0;
	for(unsigned int i =0; i < fseq_.size()-1; i++){
		val += _min_risk_tars[fseq_[i]][fseq_[i+1]];
	}
	val += _min_risk_tars[fseq_[fseq_.size()-1]][_dataset->_nb_targets+1];
	return val;
}
